package main

import (
	"context"
	_ "embed"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

//go:embed schema.sql
var schemaSQL string

// 게시물 상태.
const (
	StatusGenerating = "generating"
	StatusPending    = "pending"
	StatusApproved   = "approved"
	StatusPublishing = "publishing"
	StatusPublished  = "published"
	StatusFailed     = "failed"
	StatusHeld       = "held"
)

// 제휴사.
const (
	AffiliateCoupang = "coupang"
	AffiliateToss    = "toss"
)

type Post struct {
	ID               int64
	UserID           string
	Affiliate        string
	ProductURL       string
	AffiliateLink    string
	Memo             string
	ProductName      string
	Body             string
	Detail           string
	Detail2          string
	Status           string
	ErrorMsg         string
	ThreadPermalink  string
	ThreadPostID     string
	RepliesDone      int
	LastReplyID      string
	PublishStartedAt *time.Time
	CreatedAt        time.Time
	PublishedAt      *time.Time
}

type DB struct {
	pool *pgxpool.Pool
}

// Open은 커넥션 풀을 열고 schema.sql을 실행한다.
func Open(ctx context.Context, databaseURL string) (*DB, error) {
	pool, err := pgxpool.New(ctx, databaseURL)
	if err != nil {
		return nil, err
	}
	if _, err := pool.Exec(ctx, schemaSQL); err != nil {
		pool.Close()
		return nil, err
	}
	return &DB{pool: pool}, nil
}

func (db *DB) Close() { db.pool.Close() }

const postColumns = `id, user_id, affiliate, product_url, affiliate_link, memo, product_name, body, detail, detail2,
	status, error_msg, thread_permalink,
	thread_post_id, replies_done, last_reply_id, publish_started_at,
	created_at, published_at`

func scanPost(row pgx.Row) (*Post, error) {
	var p Post
	err := row.Scan(&p.ID, &p.UserID, &p.Affiliate, &p.ProductURL, &p.AffiliateLink, &p.Memo,
		&p.ProductName, &p.Body, &p.Detail, &p.Detail2, &p.Status, &p.ErrorMsg, &p.ThreadPermalink,
		&p.ThreadPostID, &p.RepliesDone, &p.LastReplyID, &p.PublishStartedAt,
		&p.CreatedAt, &p.PublishedAt)
	if err != nil {
		return nil, err
	}
	return &p, nil
}

// CreateDraft는 generating 상태의 row를 만들고 id를 반환한다.
func (db *DB) CreateDraft(ctx context.Context, userID, affiliate, productURL, affiliateLink, memo string) (int64, error) {
	var id int64
	err := db.pool.QueryRow(ctx,
		`INSERT INTO posts (user_id, affiliate, product_url, affiliate_link, memo, status)
		 VALUES ($1, $2, $3, $4, $5, $6) RETURNING id`,
		userID, affiliate, productURL, affiliateLink, memo, StatusGenerating).Scan(&id)
	return id, err
}

// GetPost는 그 사용자의 게시물만 반환한다. 남의 글은 없는 것과 같다.
func (db *DB) GetPost(ctx context.Context, userID string, id int64) (*Post, error) {
	return scanPost(db.pool.QueryRow(ctx,
		`SELECT `+postColumns+` FROM posts WHERE id = $1 AND user_id = $2`, id, userID))
}

// ListByStatus는 주어진 상태들의 게시물을 최신순으로 반환한다.
func (db *DB) ListByStatus(ctx context.Context, userID string, statuses ...string) ([]*Post, error) {
	rows, err := db.pool.Query(ctx,
		`SELECT `+postColumns+` FROM posts
		 WHERE user_id = $1 AND status = ANY($2) ORDER BY created_at DESC`,
		userID, statuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var posts []*Post
	for rows.Next() {
		p, err := scanPost(rows)
		if err != nil {
			return nil, err
		}
		posts = append(posts, p)
	}
	return posts, rows.Err()
}

// SetGenerated는 초안 생성이 끝난 row를 pending으로 전환한다.
func (db *DB) SetGenerated(ctx context.Context, id int64, body, detail, detail2 string) error {
	_, err := db.pool.Exec(ctx,
		`UPDATE posts SET body = $2, detail = $3, detail2 = $4, status = $5, error_msg = ''
		 WHERE id = $1`,
		id, body, detail, detail2, StatusPending)
	return err
}

// SetAutoGenerated는 AI가 상품까지 고른 초안을 저장한다.
func (db *DB) SetAutoGenerated(ctx context.Context, id int64, d AutoDraft) error {
	_, err := db.pool.Exec(ctx,
		`UPDATE posts SET product_name = $2, product_url = $3, body = $4, detail = $5,
		 detail2 = $6, status = $7, error_msg = '' WHERE id = $1`,
		id, d.ProductName, d.ProductURL, d.Body, d.Detail, d.Detail2, StatusPending)
	return err
}

// UpdateLink는 상세 화면에서 입력한 제휴 링크를 저장한다.
func (db *DB) UpdateLink(ctx context.Context, userID string, id int64, link string) error {
	_, err := db.pool.Exec(ctx,
		`UPDATE posts SET affiliate_link = $3 WHERE id = $1 AND user_id = $2`, id, userID, link)
	return err
}

// ResetForRegenerate는 카드를 비우고 다시 생성 대기 상태로 되돌린다.
func (db *DB) ResetForRegenerate(ctx context.Context, userID string, id int64) error {
	_, err := db.pool.Exec(ctx,
		`UPDATE posts SET body = '', detail = '', detail2 = '', product_name = '', product_url = '',
		 status = $3, error_msg = '' WHERE id = $1 AND user_id = $2`,
		id, userID, StatusGenerating)
	return err
}

// UpdateBody는 편집 화면에서 수정한 본문과 디테일을 저장한다.
func (db *DB) UpdateBody(ctx context.Context, userID string, id int64, body, detail, detail2 string) error {
	_, err := db.pool.Exec(ctx,
		`UPDATE posts SET body = $3, detail = $4, detail2 = $5 WHERE id = $1 AND user_id = $2`,
		id, userID, body, detail, detail2)
	return err
}

// SetStatus는 상태만 바꾼다 (보류, 재생성 등).
func (db *DB) SetStatus(ctx context.Context, userID string, id int64, status string) error {
	_, err := db.pool.Exec(ctx,
		`UPDATE posts SET status = $3 WHERE id = $1 AND user_id = $2`, id, userID, status)
	return err
}

func (db *DB) DeletePost(ctx context.Context, userID string, id int64) error {
	_, err := db.pool.Exec(ctx, `DELETE FROM posts WHERE id = $1 AND user_id = $2`, id, userID)
	return err
}

// publishableStatuses는 발행을 시작할 수 있는 상태다.
// publishing과 published가 빠져 있는 것이 중복 발행을 막는 핵심이다.
var publishableStatuses = []string{StatusPending, StatusApproved, StatusFailed, StatusHeld}

// ClaimForPublish는 한 번의 조건부 UPDATE로 발행 권한을 선점한다.
// 이미 다른 요청이 선점했으면 false를 반환한다 (중복 발행 방지, SPEC 5-2).
//
// 상태 전환을 여러 UPDATE로 쪼개면 안 된다. 예를 들어 approved로 바꾼 뒤
// 선점하면, 두 번째 요청의 approved 전환이 첫 요청의 publishing을 덮어써서
// 둘 다 통과한다. 반드시 이 한 번의 UPDATE로 끝내야 한다.
func (db *DB) ClaimForPublish(ctx context.Context, userID string, id int64) (bool, error) {
	tag, err := db.pool.Exec(ctx,
		`UPDATE posts SET status = $3, publish_started_at = now(),
		   thread_post_id = '', replies_done = 0, last_reply_id = ''
		 WHERE id = $1 AND user_id = $2 AND status = ANY($4)`,
		id, userID, StatusPublishing, publishableStatuses)
	if err != nil {
		return false, err
	}
	return tag.RowsAffected() == 1, nil
}

func (db *DB) MarkPublished(ctx context.Context, id int64, permalink string) error {
	_, err := db.pool.Exec(ctx,
		`UPDATE posts SET status = $2, thread_permalink = $3, published_at = now(), error_msg = ''
		 WHERE id = $1`,
		id, StatusPublished, permalink)
	return err
}

func (db *DB) MarkFailed(ctx context.Context, id int64, errMsg string) error {
	_, err := db.pool.Exec(ctx,
		`UPDATE posts SET status = $2, error_msg = $3 WHERE id = $1`,
		id, StatusFailed, errMsg)
	return err
}

// GetState는 app_state 값을 반환한다. 키가 없으면 빈 문자열과 false.
func (db *DB) GetState(ctx context.Context, key string) (string, bool, error) {
	var value string
	err := db.pool.QueryRow(ctx, `SELECT value FROM app_state WHERE key = $1`, key).Scan(&value)
	if err == pgx.ErrNoRows {
		return "", false, nil
	}
	if err != nil {
		return "", false, err
	}
	return value, true, nil
}

func (db *DB) SetState(ctx context.Context, key, value string) error {
	_, err := db.pool.Exec(ctx,
		`INSERT INTO app_state (key, value) VALUES ($1, $2)
		 ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now()`,
		key, value)
	return err
}

// SetGenerateError는 초안 생성이 실패했을 때 사유만 기록한다.
// 상태는 generating으로 남겨두고, 목록에서 재시도 버튼을 노출한다.
func (db *DB) SetGenerateError(ctx context.Context, id int64, errMsg string) error {
	_, err := db.pool.Exec(ctx,
		`UPDATE posts SET error_msg = $2 WHERE id = $1 AND status = $3`,
		id, errMsg, StatusGenerating)
	return err
}

// SetPublishNote는 발행은 됐지만 사용자가 알아야 할 일이 있을 때 남긴다.
// 상태는 published 그대로 둔다.
func (db *DB) SetPublishNote(ctx context.Context, id int64, note string) error {
	_, err := db.pool.Exec(ctx, `UPDATE posts SET error_msg = $2 WHERE id = $1`, id, note)
	return err
}

// ListPublished는 그 사용자의 발행 이력을 최신 발행순으로 반환한다.
func (db *DB) ListPublished(ctx context.Context, userID string) ([]*Post, error) {
	rows, err := db.pool.Query(ctx,
		`SELECT `+postColumns+` FROM posts
		 WHERE user_id = $1 AND status = $2 ORDER BY published_at DESC NULLS LAST`,
		userID, StatusPublished)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var posts []*Post
	for rows.Next() {
		p, err := scanPost(rows)
		if err != nil {
			return nil, err
		}
		posts = append(posts, p)
	}
	return posts, rows.Err()
}

// ThreadsUser는 스레드 계정 하나와 그 토큰이다.
type ThreadsUser struct {
	UserID      string
	Username    string
	AccessToken string
	ExpiresAt   time.Time
}

// SaveThreadsUser는 로그인한 사용자의 토큰을 저장한다.
func (db *DB) SaveThreadsUser(ctx context.Context, u ThreadsUser) error {
	_, err := db.pool.Exec(ctx,
		`INSERT INTO threads_users (user_id, username, access_token, expires_at)
		 VALUES ($1, $2, $3, $4)
		 ON CONFLICT (user_id) DO UPDATE SET
		   username = EXCLUDED.username,
		   access_token = EXCLUDED.access_token,
		   expires_at = EXCLUDED.expires_at,
		   updated_at = now()`,
		u.UserID, u.Username, u.AccessToken, u.ExpiresAt)
	return err
}

// GetThreadsUser는 사용자의 토큰을 읽는다. 없으면 false.
func (db *DB) GetThreadsUser(ctx context.Context, userID string) (*ThreadsUser, bool, error) {
	var u ThreadsUser
	err := db.pool.QueryRow(ctx,
		`SELECT user_id, username, access_token, expires_at FROM threads_users WHERE user_id = $1`,
		userID).Scan(&u.UserID, &u.Username, &u.AccessToken, &u.ExpiresAt)
	if err == pgx.ErrNoRows {
		return nil, false, nil
	}
	if err != nil {
		return nil, false, err
	}
	return &u, true, nil
}

func (db *DB) DeleteThreadsUser(ctx context.Context, userID string) error {
	_, err := db.pool.Exec(ctx, `DELETE FROM threads_users WHERE user_id = $1`, userID)
	return err
}

// ClearAutoDrafts는 아직 손대지 않은 자동 초안을 지운다.
//
// 자동 생성 버튼은 세 장을 통째로 새로 만드는 동작이다. 다만 제휴 링크를
// 넣어둔 초안은 사용자가 시간을 들인 것이므로 남긴다. 직접 만든 초안도
// 남긴다(메모가 있는 것으로 구분한다).
func (db *DB) ClearAutoDrafts(ctx context.Context, userID string) error {
	_, err := db.pool.Exec(ctx,
		`DELETE FROM posts
		 WHERE user_id = $1
		   AND status = ANY($2)
		   AND affiliate_link = ''
		   AND memo = ''`,
		userID, []string{StatusGenerating, StatusPending, StatusFailed})
	return err
}

// publishStaleAfter가 지나도록 publishing에 머문 글은 게시가 중간에
// 끊긴 것으로 본다. 이어서 마칠 수 있다.
const publishStaleAfter = 3 * time.Minute

// ClaimForResume은 끊긴 게시를 이어서 마칠 권한을 선점한다.
//
// publish_started_at을 다시 찍는 것이 핵심이다. 두 요청이 동시에
// 이어받으려 하면 하나만 통과한다.
func (db *DB) ClaimForResume(ctx context.Context, userID string, id int64) (bool, error) {
	tag, err := db.pool.Exec(ctx,
		`UPDATE posts SET publish_started_at = now()
		 WHERE id = $1 AND user_id = $2 AND status = $3
		   AND publish_started_at < now() - $4::interval`,
		id, userID, StatusPublishing, publishStaleAfter.String())
	if err != nil {
		return false, err
	}
	return tag.RowsAffected() == 1, nil
}

// SetPublishedBody는 본문이 올라간 직후에 그 사실을 남긴다.
// 여기서 저장하지 않으면 다음 단계에서 끊겼을 때 본문을 또 올리게 된다.
func (db *DB) SetPublishedBody(ctx context.Context, id int64, postID, permalink string) error {
	_, err := db.pool.Exec(ctx,
		`UPDATE posts SET thread_post_id = $2, thread_permalink = $3,
		   last_reply_id = $2, replies_done = 0
		 WHERE id = $1`,
		id, postID, permalink)
	return err
}

// SetReplyDone은 답글 하나가 올라갔음을 남긴다.
func (db *DB) SetReplyDone(ctx context.Context, id int64, done int, lastReplyID string) error {
	_, err := db.pool.Exec(ctx,
		`UPDATE posts SET replies_done = $2, last_reply_id = $3 WHERE id = $1`,
		id, done, lastReplyID)
	return err
}

// ListStuckPublishing은 게시가 끊긴 채 남은 글을 찾는다.
func (db *DB) ListStuckPublishing(ctx context.Context, userID string) ([]*Post, error) {
	rows, err := db.pool.Query(ctx,
		`SELECT `+postColumns+` FROM posts
		 WHERE user_id = $1 AND status = $2
		   AND publish_started_at < now() - $3::interval
		 ORDER BY id DESC`,
		userID, StatusPublishing, publishStaleAfter.String())
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var posts []*Post
	for rows.Next() {
		p, err := scanPost(rows)
		if err != nil {
			return nil, err
		}
		posts = append(posts, p)
	}
	return posts, rows.Err()
}
