package main

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"net/url"
	"strings"
	"sync"
	"testing"
)

// promptRecorder는 모델에게 간 요청 문장을 모은다.
type promptRecorder struct {
	mu      sync.Mutex
	prompts []string
}

func (p *promptRecorder) gemini(t *testing.T, reply string) *Gemini {
	t.Helper()
	g, _ := fakeGemini(t, func(w http.ResponseWriter, r *http.Request) {
		var req geminiRequest
		json.NewDecoder(r.Body).Decode(&req)
		p.mu.Lock()
		p.prompts = append(p.prompts, req.Contents[0].Parts[0].Text)
		p.mu.Unlock()
		fmt.Fprint(w, okBody(reply))
	})
	return g
}

func TestHook_세_가지_생성_모두_훅을_모델에게_알린다(t *testing.T) {
	h := hookTypes[2]
	ctx := context.Background()

	rec := &promptRecorder{}
	if _, _, err := rec.gemini(t, "본문\n---\n디테일").GenerateDraft(ctx, AffiliateCoupang, "메모", 400, h); err != nil {
		t.Fatal(err)
	}
	if _, err := rec.gemini(t, "상품\n---\n본문\n---\n답1").SuggestDrafts(ctx, AffiliateCoupang, nil, []draftSpec{{Hook: h}}); err != nil {
		t.Fatal(err)
	}
	if _, _, err := rec.gemini(t, "1\n---\n본문\n---\n답1").SuggestFromTossBatch(ctx, []TossProduct{{DisplayName: "a"}}, []hookType{h}); err != nil {
		t.Fatal(err)
	}
	if len(rec.prompts) != 3 {
		t.Fatalf("요청 %d개", len(rec.prompts))
	}
	for i, p := range rec.prompts {
		if !strings.Contains(p, "훅은 "+h.Name) || !strings.Contains(p, h.Guide) {
			t.Errorf("%d번째 요청에 훅 안내가 없다:\n%s", i, p)
		}
	}
}

func TestHook_프롬프트에_고정_구조가_남아있지_않다(t *testing.T) {
	for name, p := range map[string]string{"draft": draftSystemPrompt, "auto": autoSystemPrompt, "toss": tossSystemPrompt} {
		if strings.Contains(p, "겪던 불편 한 줄") {
			t.Errorf("%s 프롬프트에 예전 고정 구성이 남았다", name)
		}
		if !strings.Contains(p, "훅 유형") {
			t.Errorf("%s 프롬프트가 훅 유형을 따르라고 하지 않는다", name)
		}
	}
}

func TestHandleAuto_세_장을_호출_한_번에_서로_다른_훅으로_만든다(t *testing.T) {
	a := manualApp(t, nil)
	rec := &promptRecorder{}
	a.gemini = rec.gemini(t, "청소기\n---\n본문1\n---\n답1\n=====\n텀블러\n---\n본문2\n---\n답2\n=====\n수납함\n---\n본문3\n---\n답3")
	const user = "hook-batch"

	login := httptest.NewRecorder()
	a.session.issue(login, user, false)
	form := url.Values{"affiliate": {"coupang"}}
	req := httptest.NewRequest(http.MethodPost, "/auto", strings.NewReader(form.Encode()))
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	req.AddCookie(cookieFrom(t, login))
	a.handleAuto(httptest.NewRecorder(), req)

	posts, _ := a.db.ListByStatus(context.Background(), user, "", StatusGenerating, StatusPending)
	names := map[string]bool{}
	for _, p := range posts {
		t.Cleanup(func() { a.db.DeletePost(context.Background(), user, p.ID) })
		names[waitGenerated(t, a.db, user, p.ID).ProductName] = true
	}
	if len(posts) != autoBatchSize || len(names) != autoBatchSize {
		t.Fatalf("초안 %d장, 상품 %v", len(posts), names)
	}

	if len(rec.prompts) != 1 {
		t.Fatalf("모델 호출 %d번, 한 번이어야 한다", len(rec.prompts))
	}
	used := 0
	for _, h := range hookTypes {
		if strings.Contains(rec.prompts[0], "훅은 "+h.Name) {
			used++
		}
	}
	if used != autoBatchSize {
		t.Fatalf("요청에 담긴 훅 %d개, 세 장이 모두 달라야 한다:\n%s", used, rec.prompts[0])
	}
}

// 답글은 하나다. 자동 초안은 두 번째 답글을 만들지 않고, 예전 초안에 남은 것도 비운다.
func TestSingleReply_자동_초안은_답글이_하나다(t *testing.T) {
	for name, p := range map[string]string{"auto": autoSystemPrompt, "toss": tossSystemPrompt} {
		if strings.Contains(p, "[4]") || strings.Contains(p, "두 번째 답글") || !strings.Contains(p, "세 부분") {
			t.Errorf("%s 프롬프트가 아직 답글 두 개를 요구한다", name)
		}
	}

	db := openTestDB(t)
	ctx := context.Background()
	const user = "single-reply"
	id, _ := db.CreateDraft(ctx, user, AffiliateCoupang, "", "", "")
	t.Cleanup(func() { db.DeletePost(ctx, user, id) })
	db.SetGenerated(ctx, id, "옛 본문", "옛 답글", "옛 두 번째 답글")

	if err := db.SetAutoGenerated(ctx, id, AutoDraft{ProductName: "상품", Body: "본문", Detail: "답글"}); err != nil {
		t.Fatal(err)
	}
	p, _ := db.GetPost(ctx, user, id)
	if p.Detail != "답글" || p.Detail2 != "" || p.Status != StatusPending {
		t.Fatalf("초안=%+v", p)
	}
}
