package main

import (
	"context"
	"html/template"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"
)

// 검수대기는 올라갈 모양을 그대로 보여주고, 게시완료는 짧게 훑을 수 있어야 한다.
// 둘이 뒤바뀌어도 화면은 멀쩡해 보이므로 여기서 잡는다.
func TestList_탭마다_펼침이_다르다(t *testing.T) {
	tpl := template.Must(template.New("").Funcs(templateFuncs).ParseFS(templateFS, "templates/*.html"))

	render := func(tab, status string) string {
		t.Helper()
		p := &Post{ID: 7, Affiliate: AffiliateToss, ProductName: "무선 청소기",
			Body: "첫 줄\n둘째 줄\n셋째 줄\n넷째 줄", Topic: "자취",
			Status: status, AffiliateLink: "https://toss.shopping/t/1", CreatedAt: time.Now()}
		var sb strings.Builder
		data := listData{Tabs: tabs, ActiveTab: tab, Affiliates: affiliateOptions,
			Posts: []*Post{p}, BatchSize: autoBatchSize,
			Images: map[int64][]PostImage{7: {{ID: 1, Token: "tok1"}}}}
		if err := tpl.ExecuteTemplate(&sb, "list.html", data); err != nil {
			t.Fatalf("%s 렌더 실패: %v", tab, err)
		}
		return sb.String()
	}

	review := render("review", StatusPending)
	for _, want := range []string{"넷째 줄", disclosureToss, "/media/tok1", "› 자취"} {
		if !strings.Contains(review, want) {
			t.Errorf("검수대기에 %q가 없다", want)
		}
	}

	published := render("published", StatusPublished)
	if !strings.Contains(published, "첫 줄") {
		t.Error("게시완료에 본문 미리보기가 없다")
	}
	for _, unwanted := range []string{"넷째 줄", disclosureToss, "/media/tok1"} {
		if strings.Contains(published, unwanted) {
			t.Errorf("게시완료가 %q까지 펼쳤다", unwanted)
		}
	}
}

// 검수대기는 제휴사 한 곳만 보여준다. 대신 다른 쪽에 몇 장이 있는지 숫자로
// 알려준다. 그게 없으면 안 보이는 쪽에 초안이 남은 줄 모른다.
func TestList_검수대기는_제휴사_한_쪽만_보여준다(t *testing.T) {
	a := manualApp(t, nil)
	ctx := context.Background()
	const user = "aff-tabs"

	mk := func(affiliate, name string) {
		t.Helper()
		id, err := a.db.CreateDraft(ctx, user, affiliate, "", "", "")
		if err != nil {
			t.Fatal(err)
		}
		t.Cleanup(func() { a.db.DeletePost(ctx, user, id) })
		if err := a.db.SetAutoGenerated(ctx, id, AutoDraft{ProductName: name, Body: "본문"}); err != nil {
			t.Fatal(err)
		}
	}
	mk(AffiliateCoupang, "쿠팡 설거지통")
	mk(AffiliateToss, "토스 무선청소기")
	mk(AffiliateToss, "토스 텀블러")

	login := httptest.NewRecorder()
	a.session.issue(login, user, false)
	get := func(target string) string {
		t.Helper()
		req := httptest.NewRequest(http.MethodGet, target, nil)
		req.AddCookie(cookieFrom(t, login))
		w := httptest.NewRecorder()
		a.handleList(w, req)
		if w.Code != http.StatusOK {
			t.Fatalf("%s: 응답=%d", target, w.Code)
		}
		return w.Body.String()
	}

	coupang := get("/?tab=review&aff=coupang")
	if !strings.Contains(coupang, "쿠팡 설거지통") {
		t.Error("쿠팡 탭에 쿠팡 초안이 없다")
	}
	if strings.Contains(coupang, "토스 텀블러") {
		t.Error("쿠팡 탭에 토스 초안이 섞였다")
	}
	// 토스 쪽 숫자 2와, 세 장 중 두 장이 비었다는 안내가 함께 보여야 한다.
	if !strings.Contains(coupang, "토스 <em>2</em>") {
		t.Errorf("다른 제휴사 장수가 안 보인다:\n%s", tabsOf(coupang))
	}
	if !strings.Contains(coupang, "2장이 비어 있어요") {
		t.Error("빈 자리를 제휴사별로 세지 않았다")
	}

	toss := get("/?tab=review&aff=toss")
	if !strings.Contains(toss, "토스 텀블러") || !strings.Contains(toss, "토스 무선청소기") {
		t.Error("토스 탭에 토스 초안이 없다")
	}
	if strings.Contains(toss, "쿠팡 설거지통") {
		t.Error("토스 탭에 쿠팡 초안이 섞였다")
	}

	// 탭을 고르지 않으면 쿠팡부터 본다.
	if got := get("/"); !strings.Contains(got, "쿠팡 설거지통") || strings.Contains(got, "토스 텀블러") {
		t.Error("기본 탭이 쿠팡이 아니다")
	}

	// 게시완료에는 제휴사 줄이 없다. 거기선 검색으로 찾는다.
	if strings.Contains(get("/?tab=published"), "tabs-sub") {
		t.Error("게시완료에 제휴사 줄이 생겼다")
	}
}

// tabsOf는 실패 메시지에 탭 줄만 보여준다. 화면 전체를 찍으면 읽을 수 없다.
func tabsOf(html string) string {
	i := strings.Index(html, `class="tabs tabs-sub"`)
	if i < 0 {
		return "제휴사 줄이 없다"
	}
	end := strings.Index(html[i:], "</nav>")
	return html[i : i+end]
}
